# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  slides:
    if: "!contains(github.event.head_commit.message, 'slides skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Install 
      run: |
        sudo apt install ruby ruby-bundler
        bundle install
        npm install
        git clone -b 3.9.2 --depth 1 https://github.com/hakimel/reveal.js.git
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: html # The folder the action should deploy.
